version: '3'
    
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  app:
    build: .
    command: /bin/bash
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
